print('————————————————————————\033[31m CARACTERES ESPECIAIS \033[m————————————————————————')
print('\033[31mLembrando que os números devem ser digitados pelo teclado númerico (a direita das setas) no pc.\033[m\n')
opcao = int(input('Digite uma opção entre 1 e 7: '))
print()
while True:
    if opcao == 1:
        print('CARACTERES MONETÁRIOS:\n'
              '£ = ALT+0163 \n'
              '¥ = ALT+0165 \n'
              '¢ = ALT+0162 \n'
              '$ = 0024+ALT+X \n'
              '€ = ALT+0128 \n'
              '¤ = ALT+0164 ')
    elif opcao == 2:
        print('SÍMBOLOS DIVERSOS:\n'
              '© = ALT+0169 \n'
              '® = ALT+0174 \n'
              '§ = ALT+0167 \n'
              '™ = ALT+0153 \n'
              '□ = 25A1+ALT+X \n'
              '√ = 221A+ALT+X ')
    elif opcao == 3:
        print('FRAÇÕES:\n'
              '¼ = ALT+0188 \n'
              '½ = ALT+0189 \n'
              '¾ = ALT+0190 ')
    elif opcao == 4:
        print('SÍMBOLOS DA MATEMÁTICA:\n'
              '° = ALT+0176 \n'
              'º = ALT+0186 \n'
              '+ = ALT+43 \n'
              '# = ALT+35 \n'
              'µ = ALT+0181 \n'
              '< = ALT+60 \n'
              '> = ALT+62 \n'
              '% = ALT+37 \n'
              '( = ALT+40 \n'
              '[ = ALT+91 \n'
              ') = ALT+41 \n'
              '] = ALT+93 \n'
              '∆ = 2206+ALT+X ')
    elif opcao == 5:
        print('SÍMBOLOS DE PONTUAÇÃO:\n'
              '? = ALT+63 \n'
              '¿ = ALT+0191 \n'
              '! = ALT+33 \n'
              '‼ = 203+ALT+X \n'
              '- = ALT+45 \n'
              'Aspas simples = ALT+39 \n'
              'Aspas duplas = ALT+34 \n'
              ', = ALT+44 \n'
              '. = ALT+46 \n'
              '| = ALT+124 \n'
              '/ = ALT+47 \n'
              'Contra barra = ALT+92 \n'
              '` = ALT+96 \n'
              '^ = ALT+94 \n'
              '« = ALT+0171 \n'
              '» = ALT+0187 \n'
              '~ = ALT+126 \n'
              '& = ALT+38 \n'
              ': = ALT+58 \n'
              '{ = ALT+123 \n'
              '; = ALT+59 \n'
              '} = ALT+125 ')
    elif opcao == 6:
        print('SÍMBOLOS DIVERSOS:\n'
              'Æ = ALT+0198 \n'
              'æ = ALT+0230 \n'
              'ß = ALT+0223 \n'
              'ß = ALT+225 \n'
              'Œ = ALT+0140 \n'
              'œ = ALT+0156 \n'
              'ʩ = 02A9+ALT+X \n'
              'ʣ = 02A3+ALT+X \n'
              'ʥ = 02A5+ALT+X \n'
              'ʪ = 02AA+ALT+X \n'
              'ʫ = 02AB+ALT+X \n'
              'ʦ = 0246+ALT+X \n'
              'ʧ = 02A7+ALT+X \n'
              'Љ = 0409+ALT+X \n'
              'Ю = 042E+ALT+X \n'
              'Њ = 040A+ALT+X \n'
              'Ѿ = 047E+ALT+x \n'
              'Ы = 042B+ALT+X \n'
              'Ѩ = 0468+ALT+X \n'
              'Ѭ = 049C+ALT+X ')
    elif opcao == 7:
        print('EMOJIS:\n'
              '☺ = ALT+1 \n'
              '☻ = ALT+2 \n'
              '♥ = ALT+3 \n'
              '♦ = ALT+4 \n'
              '♣ = ALT+5 \n'
              '♠ = ALT+6 \n'
              '• = ALT+7 \n'
              '◘ = ALT+8 \n'
              '○ = ALT+9 \n'
              '◙ = ALT+10 \n'
              '♂ = ALT+11 \n'
              '♀ = ALT+12 \n'
              '♪ = ALT+13 \n'
              '♫ = ALT+14 \n'
              '☼ = ALT+15 \n'
              '► = ALT+16 \n'
              '◄ = ALT+17 \n'
              '↕ = ALT+18 \n'
              '‼ = ALT+19 \n'
              '¶ = ALT+20 \n'
              '▬ = ALT+22 \n'
              '↨ = ALT+23 \n'
              '↑ = ALT+24 \n'
              '↓ = ALT+25 \n'
              '→ = ALT+26 \n'
              '← = ALT+27 \n'
              '∟ = ALT+28 \n'
              '↔ = ALT+29 \n'
              '▲ = ALT+30 \n'
              '▼ = ALT+31 \n'
              'ƒ = ALT+159 \n'
              '░ = ALT+176 \n'
              '▒ = ALT+177 \n'
              '▓ = ALT+178 \n'
              '┤ = ALT+180 \n'
              '╣ = ALT+185 \n'
              '║ = ALT+186 \n'
              '╗ = ALT+187 \n'
              '╝ = ALT+188 \n'
              '├ = ALT+195 \n'
              '┼ = ALT+197 \n'
              '╚ = ALT+200 \n'
              '╔ = ALT+201 \n'
              '╩ = ALT+202 \n'
              '╦ = ALT+203 \n'
              '╠ = ALT+204 \n'
              '═ = ALT+205 \n'
              '╬ = ALT+206 \n'
              '█ = ALT+219 \n'
              '▄ = ALT+220 \n'
              '▀ = ALT+221 ')
    else:
        print('Número incorreto...')
    resp = str(input('\nQuer continuar? [S/N] '))
    if resp in 'Nn':
        print('\033[34mAté a próxima...\033[m')
        break
    else:
        opcao = int(input('\nDigite uma opção entre 1 e 7: '))
